name: Check Markdown links

on: [push]

jobs:
	test:
		name: Check Markdown links
		runs-on: ubuntu-latest
		steps:
			-   uses: actions/checkout@master
			-   name: markdown-link-check
			-   uses: gaurav-nelson/github-action-markdown-link-check@0.4.0
